- name: Copy local web source to managed servers runing RedHat or Fedora
  hosts: all
  become: true
  vars:
    os_support:
     - RedHat
     - Fedora
  tasks:
   - name: Copy source to remote host if satisfy condition
     copy:
       src: /root/sources/webapp 
       dest: /webapp 
       owner: apache
       group: apache
       mode: 0755
     loop: "{{ ansible_mounts }}"
     when:
      - ansible_distribution in os_support
      - item.mount == "/webapp" and item.size_available >= 900000000
     
