- name: Restart Rsyslog  On All Web Servers
  hosts: webserver
  become: true
  vars_files:
   - vars/service_checking.yml
  tasks:
   - name: Trying to restart rsyslog on all web servers
     service:
       name: "{{ service_name }}"
       state: "{{ service_state }}"
     
